import { ROLES } from "./roles"

// ─── Feature-Based Actions ───────────────────────────────────────────────────
export const ACTIONS = {
  // Files
  CREATE_FILE: "CREATE_FILE",
  UPDATE_FILE: "UPDATE_FILE",
  DELETE_FILE: "DELETE_FILE",
  VIEW_FILE: "VIEW_FILE",

  // File Movement
  CREATE_FILE_MOVEMENT: "CREATE_FILE_MOVEMENT",
  UPDATE_FILE_MOVEMENT: "UPDATE_FILE_MOVEMENT",
  DELETE_FILE_MOVEMENT: "DELETE_FILE_MOVEMENT",
  VIEW_FILE_MOVEMENT: "VIEW_FILE_MOVEMENT",

  // Requests
  ACCEPTED_REQUEST: "ACCEPTED_REQUEST",
  REJECTED_REQUEST: "REJECTED_REQUEST",
  PENDING_REQUEST: "PENDING_REQUEST",
  ARCHIVED_REQUEST: "ARCHIVED_REQUEST",
  REQUEST_DETAIL: "REQUEST_DETAIL",

  // Basic Info
  CREATE_BASIC_INFO: "CREATE_BASIC_INFO",
  UPDATE_BASIC_INFO: "UPDATE_BASIC_INFO",
  DELETE_BASIC_INFO: "DELETE_BASIC_INFO",
  VIEW_BASIC_INFO: "VIEW_BASIC_INFO",

  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  VIEW_DEPARTMENT: "VIEW_DEPARTMENT",

  // Taxpayers
  CREATE_TAX_PAYER: "CREATE_TAX_PAYER",
  UPDATE_TAX_PAYER: "UPDATE_TAX_PAYER",
  DELETE_TAX_PAYER: "DELETE_TAX_PAYER",
  VIEW_TAX_PAYER: "VIEW_TAX_PAYER",

  // Tax Collectors
  CREATE_TAX_COLLECTOR: "CREATE_TAX_COLLECTOR",
  UPDATE_TAX_COLLECTOR: "UPDATE_TAX_COLLECTOR",
  DELETE_TAX_COLLECTOR: "DELETE_TAX_COLLECTOR",
  VIEW_TAX_COLLECTOR: "VIEW_TAX_COLLECTOR",

  // Users
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USER: "VIEW_USER",

  // Reports
  VIEW_REPORT: "VIEW_REPORT",

  // Trash Bin
  VIEW_TRASH_BIN: "VIEW_TRASH_BIN",
  RESTORE_TRASH_BIN: "RESTORE_TRASH_BIN",
  DELETE_TRASH_BIN: "DELETE_TRASH_BIN",

  // Notifications
  CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
  VIEW_NOTIFICATION: "VIEW_NOTIFICATION",

  // Customer Service
  VIEW_CUSTOMER_SERVICE: "VIEW_CUSTOMER_SERVICE",

  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
} as const;

// ─── Permissions Matrix ──────────────────────────────────────────────────────
// Each action maps to an array of roles that are allowed to perform it.
export const PERMISSIONS: Record<string, readonly string[]> = {
  // ── Files ──────────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_FILE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.UPDATE_FILE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.DELETE_FILE]: [ROLES.ADMIN],
  [ACTIONS.VIEW_FILE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // ── File Movement ─────────────────────────────────────────────────────────
  [ACTIONS.CREATE_FILE_MOVEMENT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.UPDATE_FILE_MOVEMENT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.DELETE_FILE_MOVEMENT]: [ROLES.ADMIN],
  [ACTIONS.VIEW_FILE_MOVEMENT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],

  // ── Requests ──────────────────────────────────────────────────────────────
  [ACTIONS.PENDING_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.ACCEPTED_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.ARCHIVED_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.REJECTED_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.REQUEST_DETAIL]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // ── Basic Info ────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_BASIC_INFO]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_BASIC_INFO]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_BASIC_INFO]: [ROLES.ADMIN],
  [ACTIONS.VIEW_BASIC_INFO]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Departments ───────────────────────────────────────────────────────────
  [ACTIONS.CREATE_DEPARTMENT]: [ROLES.ADMIN],
  [ACTIONS.UPDATE_DEPARTMENT]: [ROLES.ADMIN],
  [ACTIONS.DELETE_DEPARTMENT]: [ROLES.ADMIN],
  [ACTIONS.VIEW_DEPARTMENT]: [ROLES.ADMIN],

  // ── Taxpayers ─────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_TAX_PAYER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_TAX_PAYER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_TAX_PAYER]: [ROLES.ADMIN],
  [ACTIONS.VIEW_TAX_PAYER]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Tax Collectors ────────────────────────────────────────────────────────
  [ACTIONS.CREATE_TAX_COLLECTOR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.UPDATE_TAX_COLLECTOR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.DELETE_TAX_COLLECTOR]: [ROLES.ADMIN],
  [ACTIONS.VIEW_TAX_COLLECTOR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],

  // ── Users ─────────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_USER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_USER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_USER]: [ROLES.ADMIN],
  [ACTIONS.VIEW_USER]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Reports ───────────────────────────────────────────────────────────────
  [ACTIONS.VIEW_REPORT]: [ROLES.ADMIN],

  // Trash Bin
  [ACTIONS.VIEW_TRASH_BIN]: [ROLES.ADMIN],
  [ACTIONS.RESTORE_TRASH_BIN]: [ROLES.ADMIN],
  [ACTIONS.DELETE_TRASH_BIN]: [ROLES.ADMIN],

  // ── Notifications ─────────────────────────────────────────────────────────
  [ACTIONS.CREATE_NOTIFICATION]: [ROLES.ADMIN,ROLES.MANAGER],
  [ACTIONS.UPDATE_NOTIFICATION]: [ROLES.ADMIN,ROLES.MANAGER],
  [ACTIONS.DELETE_NOTIFICATION]: [ROLES.ADMIN],
  [ACTIONS.VIEW_NOTIFICATION]: [ROLES.ADMIN,ROLES.MANAGER],

  // Customer Service
  [ACTIONS.VIEW_CUSTOMER_SERVICE]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Dashboard ─────────────────────────────────────────────────────────────
  [ACTIONS.VIEW_DASHBOARD]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE, ROLES.COLLECTOR_MANAGER],
}
