import { ROLES } from "./roles"

// ─── Feature-Based Actions ───────────────────────────────────────────────────
export const ACTIONS = {
  // Files
  CREATE_FILE: "CREATE_FILE",
  UPDATE_FILE: "UPDATE_FILE",
  DELETE_FILE: "DELETE_FILE",
  VIEW_FILE: "VIEW_FILE",

  // File Movement
  CREATE_FILE_MOVEMENT: "CREATE_FILE_MOVEMENT",
  UPDATE_FILE_MOVEMENT: "UPDATE_FILE_MOVEMENT",
  DELETE_FILE_MOVEMENT: "DELETE_FILE_MOVEMENT",
  VIEW_FILE_MOVEMENT: "VIEW_FILE_MOVEMENT",

  // Requests
  CREATE_REQUEST: "CREATE_REQUEST",
  UPDATE_REQUEST: "UPDATE_REQUEST",
  DELETE_REQUEST: "DELETE_REQUEST",
  VIEW_REQUEST: "VIEW_REQUEST",

  // Basic Info
  CREATE_BASIC_INFO: "CREATE_BASIC_INFO",
  UPDATE_BASIC_INFO: "UPDATE_BASIC_INFO",
  DELETE_BASIC_INFO: "DELETE_BASIC_INFO",
  VIEW_BASIC_INFO: "VIEW_BASIC_INFO",

  // Taxpayers
  CREATE_TAXPAYER: "CREATE_TAXPAYER",
  UPDATE_TAXPAYER: "UPDATE_TAXPAYER",
  DELETE_TAXPAYER: "DELETE_TAXPAYER",
  VIEW_TAXPAYER: "VIEW_TAXPAYER",

  // Tax Collectors
  CREATE_TAX_COLLECTOR: "CREATE_TAX_COLLECTOR",
  UPDATE_TAX_COLLECTOR: "UPDATE_TAX_COLLECTOR",
  DELETE_TAX_COLLECTOR: "DELETE_TAX_COLLECTOR",
  VIEW_TAX_COLLECTOR: "VIEW_TAX_COLLECTOR",

  // Users
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USER: "VIEW_USER",

  // Reports
  VIEW_REPORT: "VIEW_REPORT",

  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
} as const;

// ─── Permissions Matrix ──────────────────────────────────────────────────────
// Each action maps to an array of roles that are allowed to perform it.
export const PERMISSIONS: Record<string, readonly string[]> = {
  // ── Files ──────────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_FILE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.UPDATE_FILE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.DELETE_FILE]: [ROLES.ADMIN],
  [ACTIONS.VIEW_FILE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // ── File Movement ─────────────────────────────────────────────────────────
  [ACTIONS.CREATE_FILE_MOVEMENT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.UPDATE_FILE_MOVEMENT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.DELETE_FILE_MOVEMENT]: [ROLES.ADMIN],
  [ACTIONS.VIEW_FILE_MOVEMENT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],

  // ── Requests ──────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_REQUEST]: [ROLES.ADMIN],
  [ACTIONS.VIEW_REQUEST]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Basic Info ────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_BASIC_INFO]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_BASIC_INFO]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_BASIC_INFO]: [ROLES.ADMIN],
  [ACTIONS.VIEW_BASIC_INFO]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Taxpayers ─────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_TAXPAYER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_TAXPAYER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_TAXPAYER]: [ROLES.ADMIN],
  [ACTIONS.VIEW_TAXPAYER]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Tax Collectors ────────────────────────────────────────────────────────
  [ACTIONS.CREATE_TAX_COLLECTOR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.UPDATE_TAX_COLLECTOR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],
  [ACTIONS.DELETE_TAX_COLLECTOR]: [ROLES.ADMIN],
  [ACTIONS.VIEW_TAX_COLLECTOR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.COLLECTOR_MANAGER],

  // ── Users ─────────────────────────────────────────────────────────────────
  [ACTIONS.CREATE_USER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.UPDATE_USER]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.DELETE_USER]: [ROLES.ADMIN],
  [ACTIONS.VIEW_USER]: [ROLES.ADMIN, ROLES.MANAGER],

  // ── Reports ───────────────────────────────────────────────────────────────
  [ACTIONS.VIEW_REPORT]: [ROLES.ADMIN],

  // ── Dashboard ─────────────────────────────────────────────────────────────
  [ACTIONS.VIEW_DASHBOARD]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE, ROLES.COLLECTOR_MANAGER],
}
