import { ROLES } from "./roles"

export const ACTIONS = {
  DELETE: "DELETE",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  VIEW: "VIEW",
} as const;

export const PERMISSIONS = {
  [ACTIONS.DELETE]: [ROLES.ADMIN],
  [ACTIONS.UPDATE]: [ROLES.ADMIN, ROLES.MANAGER],
  [ACTIONS.CREATE]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  [ACTIONS.VIEW]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
}
