export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    ABOUT: "/about",
    AUTH: "/auth",
    RESET_PASSWORD: "/reset-password",
    UNAUTHORIZED: "/unauthorized",
  },
  DASHBOARD: {
    ROOT: "/dashboard",
    MAIN: "/dashboard/main",
    FILES: "/dashboard/files",
    FILE_MOVEMENTS: "/dashboard/file-movements",
    REQUESTS: "/dashboard/requests",
    BASIC_INFO: {
      ROOT: "/dashboard/basic-info",
      DEPARTMENTS: "/dashboard/basic-info/departments",
      ACTIVITY_TYPES: "/dashboard/basic-info/activity-types",
      PAYMENT_TYPES: "/dashboard/basic-info/payment-types",
      REGIONS: "/dashboard/basic-info/regions",
      DISTRICTS: "/dashboard/basic-info/districts",
    },
    NOTIFICATIONS: "/dashboard/notifications",
    TAXPAYERS: "/dashboard/taxpayers",
    OFFICERS: "/dashboard/officers",
    USERS: "/dashboard/users",
    USERS_CREATE: "/dashboard/users/create",
    USERS_EDIT: "/dashboard/users/:id/edit",
    USERS_SHOW: "/dashboard/users/:id",
    OPERATION_REPORTS: "/dashboard/operation-reports",
    SETTINGS: "/dashboard/settings",
  },
} as const;
